"""create signals table

Revision ID: 265dfc24bf72
Revises: acce23da3e65
Create Date: 2026-07-23 22:08:46.759251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265dfc24bf72'
down_revision: Union[str, Sequence[str], None] = 'acce23da3e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('strategy_name', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='signaldirection', native_enum=False, length=16), nullable=False),
    sa.Column('entry', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_strategy_name'), 'signals', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_strategy_name'), table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###
