"""create positions table

Revision ID: c365f1e2adc5
Revises: b79d262d7276
Create Date: 2026-07-23 22:26:28.545881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c365f1e2adc5'
down_revision: Union[str, Sequence[str], None] = 'b79d262d7276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED_STOP', 'CLOSED_TARGET', 'CLOSED_MANUAL', name='positionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'signal_id', name='uq_position_user_signal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    # ### end Alembic commands ###
